linters:
  enable-all: true
  disable:
    - lll
    - wsl
    - gomnd

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - dupl

    - path: example/main\.go
      linters:
        - dupl

    - path: backtracking/possbilities_test\.go
      linters:
        - goconst

    - path: cmd/resolve/main\.go
      text: "^G304: Potential file inclusion via variable$"
      linters:
        - gosec
