name: Publish
on:
  push:
    branches:
      - master

jobs:
  dockle:
    name: Dockle validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Build image
        run: |
          docker build --no-cache --force-rm -t dockle-ci-test:latest .
          docker image save dockle-ci-test:latest -o dockle-ci-test.tar
          chmod 666 dockle-ci-test.tar
      - name: Dockle image
        run:
          docker run -v ${{github.workspace}}/dockle-ci-test.tar:/tmp/dockle-ci-test.tar --rm goodwithtech/dockle:v0.2.4 -d --input /tmp/dockle-ci-test.tar
      - name: cleanup
        run: |
          docker image remove dockle-ci-test:latest
          rm ${{github.workspace}}/dockle-ci-test.tar

  dockerhub:
    name: Dockerhub publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: nbr41/gosudoku
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}


  gpr:
    name: Github package registry publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: "gosudoku"
          TAG: "latest"
          DOCKERFILE_PATH: "Dockerfile"
          BUILD_CONTEXT: "."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
