name: Publish
on:
  push:
    branches:
      - master

jobs:
  dockerhub:
    name: Dockerhub publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nbr41/gosudoku
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}


  gpr:
    name: Github package registry publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: "gosudoku"
          TAG: "latest"
          DOCKERFILE_PATH: "Dockerfile"
          BUILD_CONTEXT: "."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
