name: Code validation
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v ./... 
    
    - name: golangci-lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    
    - name: Run Unit tests.
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... 

    - name: Upload Coverage report to CodeCov
      uses: codecov/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
      
    
